[package]
name = "day22"
version = "0.1.0"
edition = "2021"

[dependencies]
hi_sparse_bitset = "0.3.0"
itertools = "0.12.0"
rayon = "1.8.0"
rustc-hash = "1.1.0"

[[bench]]
name = "parts"
harness = false

[dev-dependencies]
criterion = "0.5.1"
