[package]
name = "day24"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32.3"
owo-colors = "4.0.0"
z3 = { version = "0.12.1", features = ["static-link-z3"] }
